CREATE TABLE `COMMENT_FEEDBACK` (
  `COMMENT_FEEDBACK_ID` int NOT NULL AUTO_INCREMENT,
  `COMMENT_FEEDBACK_TYPE` enum('positive','negative') NOT NULL,
  `COMMENT_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`COMMENT_FEEDBACK_ID`),
  UNIQUE KEY `UNIQUE_COMMENT_FEEDBACK` (`COMMENT_ID`,`USER_ID`),
  CONSTRAINT `COMMENT_FEEDBACK_ibfk_1` FOREIGN KEY (`COMMENT_ID`) REFERENCES `VIDEO_COMMENT` (`COMMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO COMMENT_FEEDBACK VALUES('1','negative','1','1');


CREATE TABLE `USER` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_USERNAME` varchar(25) NOT NULL,
  `USER_PASSWORD` varchar(25) NOT NULL,
  `USER_PROFILEPICTURE` varchar(100) DEFAULT NULL,
  `USER_PROFILEDESCRIPTION` varchar(1000) DEFAULT NULL,
  `USER_DATETIMECREATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_LASTUPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UNIQUE_USERNAME` (`USER_USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO USER VALUES('1','maxmustermann','passwort123','https://picsum.photos/50/50','Ich bin Max und ich liebe es, Videos zu machen!','2023-04-05 11:39:26','2023-04-05 11:39:26');


CREATE TABLE `USER_FOLLOWING` (
  `FOLLOWING_ID` int NOT NULL AUTO_INCREMENT,
  `FOLLOWING_SUBSCRIBER` int NOT NULL,
  `FOLLOWING_SUBSCRIBED` int NOT NULL,
  PRIMARY KEY (`FOLLOWING_ID`),
  UNIQUE KEY `UNIQUE_FOLLOWING` (`FOLLOWING_SUBSCRIBER`,`FOLLOWING_SUBSCRIBED`),
  KEY `FOLLOWING_SUBSCRIBED` (`FOLLOWING_SUBSCRIBED`),
  CONSTRAINT `USER_FOLLOWING_ibfk_1` FOREIGN KEY (`FOLLOWING_SUBSCRIBER`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `USER_FOLLOWING_ibfk_2` FOREIGN KEY (`FOLLOWING_SUBSCRIBED`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO USER_FOLLOWING VALUES('1','1','1');


CREATE TABLE `USER_SOCIAL` (
  `SOCIAL_ID` int NOT NULL AUTO_INCREMENT,
  `SOCIAL_PLATFORM` varchar(25) NOT NULL,
  `SOCIAL_URL` varchar(250) NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`SOCIAL_ID`),
  UNIQUE KEY `UNIQUE_SOCIAL` (`SOCIAL_PLATFORM`,`SOCIAL_URL`,`USER_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `USER_SOCIAL_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO USER_SOCIAL VALUES('1','Twitter','https://github.com/jonasfroeller','1');


CREATE TABLE `VIDEO` (
  `VIDEO_ID` int NOT NULL AUTO_INCREMENT,
  `VIDEO_TITLE` varchar(25) NOT NULL,
  `VIDEO_DESCRIPTION` varchar(500) DEFAULT NULL,
  `VIDEO_LOCATION` varchar(250) NOT NULL,
  `VIDEO_SIZE` varchar(6) NOT NULL,
  `VIDEO_VIEWS` int DEFAULT '0',
  `VIDEO_SHARES` int DEFAULT '0',
  `VIDEO_DATETIMEPOSTED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `VIDEO_LASTUPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`VIDEO_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `VIDEO_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO VIDEO VALUES('1','Mein erster Vlog','Hier ist mein erster Vlog, den ich jemals gemacht habe!','https://www.youtube.com/watch?v=dQw4w9WgXcQ','25MB','0','0','2023-04-05 11:39:26','2023-04-05 11:39:26','1');


CREATE TABLE `VIDEO_COMMENT` (
  `COMMENT_ID` int NOT NULL AUTO_INCREMENT,
  `COMMENT_PARENT_ID` int DEFAULT NULL,
  `COMMENT_MESSAGE` varchar(250) NOT NULL,
  `COMMENT_DATETIMEPOSTED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENT_LASTUPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VIDEO_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  KEY `VIDEO_ID` (`VIDEO_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `VIDEO_COMMENT_ibfk_1` FOREIGN KEY (`VIDEO_ID`) REFERENCES `VIDEO` (`VIDEO_ID`),
  CONSTRAINT `VIDEO_COMMENT_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO VIDEO_COMMENT VALUES('1','NULL','Tolles Video!','2023-04-05 11:39:26','2023-04-05 11:39:26','1','1');


CREATE TABLE `VIDEO_FEEDBACK` (
  `VIDEO_FEEDBACK_ID` int NOT NULL AUTO_INCREMENT,
  `VIDEO_FEEDBACK_TYPE` enum('positive','negative') NOT NULL,
  `VIDEO_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  PRIMARY KEY (`VIDEO_FEEDBACK_ID`),
  UNIQUE KEY `UNIQUE_VIDEO_FEEDBACK` (`VIDEO_ID`,`USER_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `VIDEO_FEEDBACK_ibfk_1` FOREIGN KEY (`VIDEO_ID`) REFERENCES `VIDEO` (`VIDEO_ID`),
  CONSTRAINT `VIDEO_FEEDBACK_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO VIDEO_FEEDBACK VALUES('1','positive','1','1');


CREATE TABLE `VIDEO_HASHTAG` (
  `HASHTAG_ID` int NOT NULL AUTO_INCREMENT,
  `HASHTAG_NAME` varchar(500) NOT NULL,
  `VIDEO_ID` int NOT NULL,
  PRIMARY KEY (`HASHTAG_ID`),
  UNIQUE KEY `UNIQUE_HASHTAG` (`VIDEO_ID`,`HASHTAG_NAME`),
  CONSTRAINT `VIDEO_HASHTAG_ibfk_1` FOREIGN KEY (`VIDEO_ID`) REFERENCES `VIDEO` (`VIDEO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO VIDEO_HASHTAG VALUES('1','Vlog','1');
