@startuml database
!define table(x) class x << (T,#FFAAAA) >>
!define PK(x) <b><u>x</u></b>
!define FK(x) <u>x</u>
!define NOT_NULL(x) <b><i>x</i></b>
!define DEFAULT(x) <i>x</i>

left to right direction
skinparam roundcorner 5
skinparam linetype ortho /' polyline '/
skinparam shadowing false
skinparam handwritten false
skinparam class {
  BackgroundColor white
  ArrowColor #2688d4
  ArrowThickness 2
  BorderColor #2688d4
}

table(USER) {
  PK(USER_ID INT AUTO_INCREMENT)
  NOT_NULL(USER_USERNAME VARCHAR(25))
  NOT_NULL(USER_PASSWORD VARCHAR(250))
  DEFAULT(USER_PROFILEPICTURE VARCHAR(100))
  DEFAULT(USER_PROFILEDESCRIPTION VARCHAR(1000))
  DEFAULT(USER_DATETIMECREATED TIMESTAMP)
  DEFAULT(USER_LASTUPDATE TIMESTAMP)
  CONSTRAINT UNIQUE_USERNAME UNIQUE (USER_USERNAME)
}

table(VIDEO) {
  PK(VIDEO_ID INT AUTO_INCREMENT)
  NOT_NULL(VIDEO_TITLE VARCHAR(25))
  DEFAULT(VIDEO_DESCRIPTION VARCHAR(500))
  NOT_NULL(VIDEO_LOCATION VARCHAR(250))
  NOT_NULL(VIDEO_SIZE VARCHAR(6))
  DEFAULT(VIDEO_VIEWS INT)
  DEFAULT(VIDEO_SHARES INT)
  DEFAULT(VIDEO_DATETIMEPOSTED TIMESTAMP)
  DEFAULT(VIDEO_LASTUPDATE TIMESTAMP)
  FK(USER_ID INT)
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
}

table(USER_SOCIAL) {
  PK(SOCIAL_ID INT AUTO_INCREMENT)
  NOT_NULL(SOCIAL_PLATFORM VARCHAR(25))
  NOT_NULL(SOCIAL_URL VARCHAR(250))
  FK(USER_ID INT)
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
  CONSTRAINT UNIQUE_SOCIAL UNIQUE (SOCIAL_PLATFORM, SOCIAL_URL, USER_ID)
}

table(USER_FOLLOWING) {
  PK(FOLLOWING_ID INT AUTO_INCREMENT)
  FK(FOLLOWING_SUBSCRIBER INT)
  FK(FOLLOWING_SUBSCRIBED INT)
  FOREIGN KEY (FOLLOWING_SUBSCRIBER) REFERENCES USER(USER_ID)
  FOREIGN KEY (FOLLOWING_SUBSCRIBED) REFERENCES USER(USER_ID)
  CONSTRAINT UNIQUE_FOLLOWING UNIQUE (FOLLOWING_SUBSCRIBER, FOLLOWING_SUBSCRIBED)
}

table(VIDEO_FEEDBACK) {
  PK(VIDEO_FEEDBACK_ID INT AUTO_INCREMENT)
  NOT_NULL(VIDEO_FEEDBACK_TYPE ENUM('positive', 'negative'))
  FK(VIDEO_ID INT)
  FK(USER_ID INT)
  FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
  CONSTRAINT UNIQUE_VIDEO_FEEDBACK UNIQUE (VIDEO_ID, USER_ID)
}

table(COMMENT_FEEDBACK) {
  PK(COMMENT_FEEDBACK_ID INT AUTO_INCREMENT)
  NOT_NULL(COMMENT_FEEDBACK_TYPE ENUM('positive', 'negative'))
  FK(COMMENT_ID INT)
  FK(USER_ID INT)
  FOREIGN KEY (COMMENT_ID) REFERENCES VIDEO_COMMENT(COMMENT_ID)
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
  CONSTRAINT UNIQUE_COMMENT_FEEDBACK UNIQUE (COMMENT_ID, USER_ID)
}

table(VIDEO_HASHTAG) {
  PK(HASHTAG_ID INT AUTO_INCREMENT)
  NOT_NULL(HASHTAG_NAME VARCHAR(500))
  FK(VIDEO_ID INT)
  FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
  CONSTRAINT UNIQUE_HASHTAG UNIQUE (VIDEO_ID, HASHTAG_NAME)
}

table(VIDEO_COMMENT) {
  PK(COMMENT_ID INT AUTO_INCREMENT)
  DEFAULT(COMMENT_PARENT_ID INT)
  NOT_NULL(COMMENT_MESSAGE VARCHAR(250))
  DEFAULT(COMMENT_DATETIMEPOSTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
  DEFAULT(COMMENT_LASTUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
  FK(VIDEO_ID INT NOT NULL)
  FK(USER_ID INT NOT NULL)
  FK VIDEO(VIDEO_ID)
  FK USER(USER_ID)
}

USER_FOLLOWING -> USER: FOLLOWING_SUBSCRIBER
USER_FOLLOWING -> USER: FOLLOWING_SUBSCRIBED
VIDEO -> USER: USER_ID
USER_SOCIAL -> USER: USER_ID
VIDEO_FEEDBACK -> VIDEO: VIDEO_ID
VIDEO_FEEDBACK -> USER: USER_ID
COMMENT_FEEDBACK -> VIDEO_COMMENT: COMMENT_ID
COMMENT_FEEDBACK -> USER: USER_ID
VIDEO_HASHTAG -> VIDEO: VIDEO_ID
VIDEO_COMMENT -> USER: USER_ID
VIDEO_COMMENT -> VIDEO: VIDEO_ID
VIDEO_COMMENT -> VIDEO_COMMENT: COMMENT_PARENT_ID

@enduml
