// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Sidebar: {
		/**
		 * S​t​a​r​t​s​e​i​t​e
		 */
		home: string
		/**
		 * S​u​c​h​e
		 */
		search: string
		/**
		 * K​o​n​t​o
		 */
		account: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		settings: string
	}
	pages: {
		home: {
			/**
			 * A​n​m​e​l​d​e​n
			 */
			logIn: string
			/**
			 * A​b​m​e​l​d​e​n
			 */
			logOut: string
		}
	}
}

export type TranslationFunctions = {
	Sidebar: {
		/**
		 * Startseite
		 */
		home: () => LocalizedString
		/**
		 * Suche
		 */
		search: () => LocalizedString
		/**
		 * Konto
		 */
		account: () => LocalizedString
		/**
		 * Einstellungen
		 */
		settings: () => LocalizedString
	}
	pages: {
		home: {
			/**
			 * Anmelden
			 */
			logIn: () => LocalizedString
			/**
			 * Abmelden
			 */
			logOut: () => LocalizedString
		}
	}
}

export type Formatters = {}
