// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	LangSelect: {
		/**
		 * S​p​r​a​c​h​e
		 */
		lang: string
	}
	ThemeSelect: {
		/**
		 * S​t​i​l
		 */
		theme: string
	}
	Sidebar: {
		/**
		 * S​t​a​r​t​s​e​i​t​e
		 */
		home: string
		/**
		 * S​u​c​h​e
		 */
		search: string
		/**
		 * K​o​n​t​o
		 */
		account: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		settings: string
	}
	Header: {
		/**
		 * A​n​m​e​l​d​e​n
		 */
		logIn: string
		/**
		 * A​b​m​e​l​d​e​n
		 */
		logOut: string
	}
	SignInUp: {
	}
	VideoResult: {
		/**
		 * {​{​k​e​i​n​e​ ​F​o​l​l​o​w​e​r​|​e​i​n​ ​F​o​l​l​o​w​e​r​|​?​?​ ​F​o​l​l​o​w​e​r​}​}
		 */
		follower: string
		/**
		 * {​{​k​e​i​n​e​ ​L​i​k​e​s​|​e​i​n​ ​L​i​k​e​|​?​?​ ​L​i​k​e​s​}​}
		 */
		likes: string
		/**
		 * {​{​k​e​i​n​e​ ​V​i​e​w​s​|​e​i​n​ ​V​i​e​w​|​?​?​ ​V​i​e​w​s​}​}
		 */
		views: string
		/**
		 * k​e​i​n​e​ ​t​a​g​s
		 */
		no_tags: string
	}
	VideoSection: {
		/**
		 * {​{​k​e​i​n​e​ ​F​o​l​l​o​w​e​r​|​e​i​n​ ​F​o​l​l​o​w​e​r​|​?​?​ ​F​o​l​l​o​w​e​r​}​}
		 */
		follower: string
		/**
		 * {​{​k​e​i​n​e​ ​V​i​e​w​s​|​e​i​n​ ​V​i​e​w​|​?​?​ ​V​i​e​w​s​}​}
		 */
		views: string
		/**
		 * {​{​F​o​l​g​e​n​|​G​e​f​o​l​g​t​}​}
		 */
		subscribe: string
	}
	InfoSection: {
		/**
		 * B​e​s​c​h​r​e​i​b​u​n​g
		 */
		description: string
		/**
		 * K​o​m​m​e​n​t​a​r​e
		 */
		comments: string
		/**
		 * {​{​k​e​i​n​e​ ​K​o​m​m​e​n​t​a​r​e​|​e​i​n​ ​K​o​m​m​e​n​t​a​r​|​?​?​ ​K​o​m​m​e​n​t​a​r​e​}​}
		 */
		comments_amount: string
		/**
		 * g​e​p​o​s​t​e​t​ ​a​m
		 */
		posted_on: string
	}
	CommentPost: {
		/**
		 * r​e​p​l​y
		 */
		reply: string
		/**
		 * {​r​e​p​l​i​e​s​}​ ​A​n​t​w​o​r​t​e​n
		 * @param {unknown} replies
		 */
		replies: RequiredParams<'replies'>
	}
	UserData: {
		/**
		 * {​{​k​e​i​n​e​ ​V​i​d​e​o​s​|​e​i​n​ ​V​i​d​e​o​|​?​?​ ​V​i​d​e​o​s​}​}
		 */
		videos: string
		/**
		 * {​{​k​e​i​n​e​ ​F​o​l​l​o​w​e​r​|​e​i​n​ ​F​o​l​l​o​w​e​r​|​?​?​ ​F​o​l​l​o​w​e​r​}​}
		 */
		follower: string
		/**
		 * {​{​k​e​i​n​e​ ​L​i​k​e​s​|​e​i​n​ ​L​i​k​e​|​?​?​ ​L​i​k​e​s​}​}
		 */
		likes: string
		/**
		 * {​{​k​e​i​n​e​ ​V​i​e​w​s​|​e​i​n​ ​V​i​e​w​|​?​?​ ​V​i​e​w​s​}​}
		 */
		views: string
		/**
		 * B​e​i​g​e​t​r​e​t​e​n​ ​a​m​ 
		 */
		joined: string
		/**
		 * B​e​a​r​b​e​i​t​e​n​ 
		 */
		edit: string
		/**
		 * P​o​s​t​e​n​ 
		 */
		post: string
		/**
		 * M​e​h​r​ ​l​e​s​e​n​ 
		 */
		more: string
	}
	Popups: {
	}
	pages: {
		account: {
			/**
			 * S​u​c​h​e​ ​n​a​c​h​:
			 */
			subject: string
			/**
			 * K​a​t​e​g​o​r​i​e
			 */
			category: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * T​i​t​e​l
			 */
			title: string
			/**
			 * S​o​r​t​i​e​r​e​ ​n​a​c​h​:
			 */
			sort_by: string
			/**
			 * D​a​t​u​m
			 */
			date: string
			/**
			 * A​u​f​r​u​f​e​n
			 */
			views: string
			/**
			 * L​i​k​e​s
			 */
			likes: string
			/**
			 * {​{​e​i​n​ ​V​i​d​e​o​ ​g​e​f​u​n​d​e​n​}​}
			 */
			videos_found: string
		}
		settings: {
			site_section: {
				/**
				 * S​e​i​t​e​n​ ​E​i​n​s​t​e​l​l​u​n​g​e​n​:
				 */
				title: string
			}
			acount_section: {
				/**
				 * A​c​c​o​u​n​t​ ​E​i​n​s​t​e​l​l​u​n​g​e​n​:
				 */
				title: string
				/**
				 * B​e​s​c​h​r​e​i​b​u​n​g​:
				 */
				description: string
				/**
				 * U​s​e​r​n​a​m​e​:
				 */
				username: string
				/**
				 * P​a​s​s​w​o​r​t​:
				 */
				password: string
				/**
				 * S​o​z​i​a​l​e​ ​M​e​d​i​e​n​:
				 */
				socials: string
				/**
				 * B​e​a​r​b​e​i​t​e​n
				 */
				edit: string
			}
		}
	}
	global: {
		/**
		 * S​u​c​h​e​n
		 */
		search: string
	}
}

export type TranslationFunctions = {
	LangSelect: {
		/**
		 * Sprache
		 */
		lang: () => LocalizedString
	}
	ThemeSelect: {
		/**
		 * Stil
		 */
		theme: () => LocalizedString
	}
	Sidebar: {
		/**
		 * Startseite
		 */
		home: () => LocalizedString
		/**
		 * Suche
		 */
		search: () => LocalizedString
		/**
		 * Konto
		 */
		account: () => LocalizedString
		/**
		 * Einstellungen
		 */
		settings: () => LocalizedString
	}
	Header: {
		/**
		 * Anmelden
		 */
		logIn: () => LocalizedString
		/**
		 * Abmelden
		 */
		logOut: () => LocalizedString
	}
	SignInUp: {
	}
	VideoResult: {
		/**
		 * {{keine Follower|ein Follower|?? Follower}}
		 */
		follower: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Likes|ein Like|?? Likes}}
		 */
		likes: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Views|ein View|?? Views}}
		 */
		views: (arg0: number | string | boolean) => LocalizedString
		/**
		 * keine tags
		 */
		no_tags: () => LocalizedString
	}
	VideoSection: {
		/**
		 * {{keine Follower|ein Follower|?? Follower}}
		 */
		follower: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Views|ein View|?? Views}}
		 */
		views: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{Folgen|Gefolgt}}
		 */
		subscribe: (arg0: number | string | boolean) => LocalizedString
	}
	InfoSection: {
		/**
		 * Beschreibung
		 */
		description: () => LocalizedString
		/**
		 * Kommentare
		 */
		comments: () => LocalizedString
		/**
		 * {{keine Kommentare|ein Kommentar|?? Kommentare}}
		 */
		comments_amount: (arg0: number | string | boolean) => LocalizedString
		/**
		 * gepostet am
		 */
		posted_on: () => LocalizedString
	}
	CommentPost: {
		/**
		 * reply
		 */
		reply: () => LocalizedString
		/**
		 * {replies} Antworten
		 */
		replies: (arg: { replies: unknown }) => LocalizedString
	}
	UserData: {
		/**
		 * {{keine Videos|ein Video|?? Videos}}
		 */
		videos: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Follower|ein Follower|?? Follower}}
		 */
		follower: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Likes|ein Like|?? Likes}}
		 */
		likes: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{keine Views|ein View|?? Views}}
		 */
		views: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Beigetreten am 
		 */
		joined: () => LocalizedString
		/**
		 * Bearbeiten 
		 */
		edit: () => LocalizedString
		/**
		 * Posten 
		 */
		post: () => LocalizedString
		/**
		 * Mehr lesen 
		 */
		more: () => LocalizedString
	}
	Popups: {
	}
	pages: {
		account: {
			/**
			 * Suche nach:
			 */
			subject: () => LocalizedString
			/**
			 * Kategorie
			 */
			category: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Titel
			 */
			title: () => LocalizedString
			/**
			 * Sortiere nach:
			 */
			sort_by: () => LocalizedString
			/**
			 * Datum
			 */
			date: () => LocalizedString
			/**
			 * Aufrufen
			 */
			views: () => LocalizedString
			/**
			 * Likes
			 */
			likes: () => LocalizedString
			/**
			 * {{ein Video gefunden}}
			 */
			videos_found: (arg: { keine Videos gefunden: number | string | boolean }) => LocalizedString
		}
		settings: {
			site_section: {
				/**
				 * Seiten Einstellungen:
				 */
				title: () => LocalizedString
			}
			acount_section: {
				/**
				 * Account Einstellungen:
				 */
				title: () => LocalizedString
				/**
				 * Beschreibung:
				 */
				description: () => LocalizedString
				/**
				 * Username:
				 */
				username: () => LocalizedString
				/**
				 * Passwort:
				 */
				password: () => LocalizedString
				/**
				 * Soziale Medien:
				 */
				socials: () => LocalizedString
				/**
				 * Bearbeiten
				 */
				edit: () => LocalizedString
			}
		}
	}
	global: {
		/**
		 * Suchen
		 */
		search: () => LocalizedString
	}
}

export type Formatters = {}
